@host=http://localhost:8800
@id=b534ca64-be45-421a-af43-e5dfc38daa3d
@id-token=eyJ1c2VyX2lkIjoiNjk4YmM2OWMtMGFiMS00YzQyLWFhODctMTY0MWY3MTY3YjQ2IiwiaWRlbnRpdHkiOiJ1c2VyQG1haWwuY29tIiwicm9sZSI6InVzZXIifQ==
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAbWFpbC5jb20iLCJleHAiOjE2NjA1NTQ4MTMsImlhdCI6MTY2MDU1MzkxMywicm9sZSI6InVzZXIiLCJzdWIiOiJlMzEzMjUyZC1hN2UwLTRlYWUtODcxMi1jZmE5ZWE4ZmE4MDEiLCJ1c2VyX2lkIjoiNDEyZjdhNjctYjM4Mi00NWRkLTgzZDUtMGMxMTVkNmZmMWRhIn0.VUcfrv0t6SaRRRvMVmF4aVynv29DvSm-1BO4FWinv6s

### create
POST {{host}}/api/v1/todos/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "text": "abc"
}

### list all
GET {{host}}/api/v1/todos/
Authorization: Bearer {{token}}

### list with filter
GET {{host}}/api/v1/todos/?term=&completed=0
Authorization: Bearer {{token}}

### list all completed
GET {{host}}/api/v1/todos?completed=1
Authorization: Bearer {{token}}

### list all uncompleted
GET {{host}}/api/v1/todos?completed=0
Authorization: Bearer {{token}}

### get by id
GET {{host}}/api/v1/todos/{{id}}
Authorization: Bearer {{token}}

### update status
PATCH  {{host}}/api/v1/todos/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "completed": true
}
### delete by id
DELETE {{host}}/api/v1/todos/{{id}}
Authorization: Bearer {{token}}