@host=http://localhost:8080

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAbWFpbC5jb20iLCJleHAiOjE2NjAyMDcxNTgsImlhdCI6MTY2MDIwNjg1OCwicm9sZSI6InVzZXIiLCJzdWIiOiIyNDhiYTNhMS0wM2EzLTQ2YTAtYmJlOS04ZDIzNTkyY2E4MTEiLCJ1c2VyX2lkIjoiNjk4YmM2OWMtMGFiMS00YzQyLWFhODctMTY0MWY3MTY3YjQ2In0.UU1urmjXf2swc9rb-OdVeaUJNcoTNqHJo0YA5EmllFY


### register
POST {{host}}/api/v1/auth/register
Content-Type: application/json

{
  "email": "user@mail.com",
  "password": "user"
}

### login
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "user@mail.com",
  "password": "user"
}

### profile
GET {{host}}/api/v1/auth/profile
Authorization: Bearer {{token}}

### update profile
PATCH  {{host}}/api/v1/auth/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "password_old": "1234",
  "password_new": "user"
}

### verify
GET  {{host}}/api/v1/auth/verify
Authorization: Bearer {{token}}
