@host=http://localhost:8080

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAbWFpbC5jb20iLCJyb2xlIjoidXNlciIsInN1YiI6ImY4NjE5MzZjLTA2MmYtNGU0OS04MmE4LTA4ZjM5YWJlZGRhOSIsImlhdCI6MTY1OTUyMDU5MH0.NHT8oZXrrQOVXUCepiNCfajRKE3brkqamT3eUk2MawA


### register
POST {{host}}/api/v1/auth/register
Content-Type: application/json

{
  "email": "user@mail.com",
  "password": "user"
}

### login
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "admin"
}

### profile
GET {{host}}/api/v1/auth/profile
Authorization: Bearer {{token}}

### update profile
PATCH  {{host}}/api/v1/auth/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "password_old": "1234",
  "password_new": "user"
}
